//
//  SwiftFeatureRuntimeTests.swift
//  ZenCODE
//
//  Created by Gerardo Grisolini on 30/05/26.
//
import Foundation
@testable import ZenCODECore
import Testing

extension SwiftFeatureRuntimeTests {
    @Test
    func processRunnerWritesStandardInput() async throws {
        let result = try await AsyncProcessRunner.run(
            executableURL: URL(fileURLWithPath: "/bin/cat"),
            arguments: [],
            stdinData: Data("hello feature\n".utf8),
            timeout: 10
        )

        #expect(result.exitCode == 0)
        #expect(result.stdout == "hello feature\n")
    }

    @Test
    func registryDiscoversExecutableManifest() throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("swift-feature-registry-\(UUID().uuidString)", isDirectory: true)
        let featureURL = rootURL.appendingPathComponent("example", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }

        try FileManager.default.createDirectory(
            at: featureURL,
            withIntermediateDirectories: true
        )
        let executableURL = featureURL.appendingPathComponent("feature")
        try "#!/bin/sh\n".write(to: executableURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )
        try """
        {
          "id": "example",
          "enabled": true,
          "executable": "feature",
          "tools": [
            {
              "name": "feature.example.echo",
              "description": "Echo test",
              "inputSchema": {
                "type": "object",
                "properties": {
                  "text": { "type": "string" }
                },
                "required": ["text"]
              }
            }
          ]
        }
        """.write(
            to: featureURL.appendingPathComponent(SwiftFeatureRegistry.manifestFilename),
            atomically: true,
            encoding: .utf8
        )

        let bundles = SwiftFeatureRegistry.discoverFeatureBundles(
            searchRoots: [rootURL]
        )

        #expect(bundles.count == 1)
        #expect(bundles.first?.id == "example")
        #expect(bundles.first?.tools.first?.name == "feature.example.echo")
        #expect(bundles.first?.tools.first?.requiredInputArgumentNames() == ["text"])
    }

    @Test
    func registrySupportsGeneratedFeaturePackageManifestSchema() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("swift-feature-schema-\(UUID().uuidString)", isDirectory: true)
        let featureURL = rootURL.appendingPathComponent("rich", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }

        try FileManager.default.createDirectory(
            at: featureURL,
            withIntermediateDirectories: true
        )
        let executableURL = featureURL.appendingPathComponent("feature")
        try """
        #!/bin/sh
        if [ "$1" = "--list-tools" ]; then
          printf '{"tools":[{"name":"custom.dynamic","description":"Dynamic custom tool","inputSchema":"{}"}]}\n'
          exit 0
        fi
        cat >/dev/null
        printf '{"ok":true,"output":"custom-output"}\n'
        """.write(to: executableURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )
        try """
        {
          "schemaVersion": 1,
          "id": "custom-feature",
          "displayName": "Custom Feature",
          "description": "Feature generated by an agent.",
          "enabled": true,
          "executable": "feature",
          "discoversToolsAtRuntime": true,
          "toolNamePrefixes": ["custom."],
          "toolNameAliases": ["CustomDynamic"],
          "build": {
            "system": "swiftpm",
            "packagePath": ".",
            "product": "custom-feature",
            "configuration": "release",
            "executablePath": ".build/release/custom-feature"
          },
          "generated": {
            "by": "ZenCODE",
            "prompt": "Need a custom feature",
            "createdAt": "2026-05-30T12:00:00Z"
          },
          "tools": []
        }
        """.write(
            to: featureURL.appendingPathComponent(SwiftFeatureRegistry.manifestFilename),
            atomically: true,
            encoding: .utf8
        )

        let bundles = SwiftFeatureRegistry.discoverFeatureBundles(
            searchRoots: [rootURL]
        )
        #expect(bundles.first?.id == "custom-feature")
        #expect(bundles.first?.toolNamePrefixes == ["custom."])
        #expect(bundles.first?.toolNameAliases == ["CustomDynamic"])
        #expect(bundles.first?.discoversToolsAtRuntime == true)

        let runtime = SwiftFeatureRuntime(featureSearchRoots: [rootURL])
        let statuses = await runtime.featureStatuses()
        #expect(statuses.first?.displayName == "Custom Feature")
        #expect(statuses.first?.description == "Feature generated by an agent.")
        #expect(statuses.first?.build?.product == "custom-feature")
        #expect(statuses.first?.generated?.by == "ZenCODE")

        let descriptors = await runtime.descriptors(
            allowedToolNames: ["custom."]
        )
        #expect(descriptors.map(\.name) == ["custom.dynamic"])
    }
}
