//
//  MemoryDeduplication.swift
//  ZenCODE
//
//  How a write decides that an active entry already carries the same durable
//  fact.
//

import Foundation

/// The `Timestamp:` line `memory.write` prepends when its caller omitted one.
///
/// The annotation is *generated*, not authored: the same durable fact written
/// again on a later turn — or from another time zone — differs only by this
/// line and would otherwise be stored twice. Deduplication may therefore ignore
/// this line, and only this line.
///
/// Everything else that looks like a timestamp is content: a `Timestamp:` the
/// caller wrote deliberately, one inside a fenced code block, one quoted from a
/// log. Those must keep two entries distinct, so this type is deliberately
/// narrow — it matches one position (the first line) and one rendering (the one
/// `MemoryService.timestampString` produces, verified by round-trip).
enum MemoryAutoTimestamp {
    /// Exact prefix `memory.write` emits, including the separating space.
    static let fieldPrefix = "Timestamp: "

    /// Renders the annotation exactly as `memory.write` writes it.
    static func line(for date: Date, timeZone: TimeZone) -> String {
        fieldPrefix + MemoryService.timestampString(date, timeZone: timeZone)
    }

    /// Whether `line` is something this tool could have generated itself.
    ///
    /// The value must be the machine shape `yyyy-MM-dd HH:mm ZoneIdentifier`
    /// *and* round-trip through ``MemoryService/timestampString(_:timeZone:)``.
    /// `Timestamp: yesterday`, `Timestamp: 2026-05-27`, a localized rendering or
    /// an unknown zone are all authored content and are never ignored.
    static func isGeneratedLine(_ line: String) -> Bool {
        guard line.hasPrefix(fieldPrefix) else { return false }
        let value = String(line.dropFirst(fieldPrefix.count))
        let components = value.split(separator: " ", omittingEmptySubsequences: false)
        guard components.count == 3,
              let timeZone = TimeZone(identifier: String(components[2])),
              let date = MemoryEntryMetadata.date(fromTimestamp: value) else {
            return false
        }
        return MemoryService.timestampString(date, timeZone: timeZone) == value
    }

    /// `content` without its generated first line, or `nil` when it does not
    /// start with one.
    ///
    /// Only the first line is examined, because that is the only position
    /// `memory.write` inserts at. A `Timestamp:` further down — a second field,
    /// a code block, a quoted excerpt — is never removed.
    static func strippingGeneratedLine(from content: String) -> String? {
        let lines = content.components(separatedBy: .newlines)
        guard lines.count > 1, isGeneratedLine(lines[0]) else { return nil }
        return lines.dropFirst().joined(separator: "\n")
    }
}

/// What a write compares against the active entries of the graph.
///
/// The key carries the caller's *intent* rather than guessing it from the text:
/// only the code path that generated a timestamp is allowed to have that line
/// ignored. Every other caller — the legacy `MemoryService.writeEntry` API,
/// `learn`, a caller that supplied its own `Timestamp:` — is compared
/// literally.
struct MemoryDeduplicationKey: Sendable {
    /// Normalized content exactly as it will be stored.
    let literal: String
    /// The same content minus the `Timestamp:` line *this write generated*.
    /// `nil` means "no line may be ignored".
    let withoutGeneratedTimestamp: String?

    /// Key for content whose every line is caller-authored.
    static func literal(_ content: String) -> MemoryDeduplicationKey {
        MemoryDeduplicationKey(literal: content, withoutGeneratedTimestamp: nil)
    }

    /// Key for content `memory.write` stamped itself.
    static func autoTimestamped(_ content: String) -> MemoryDeduplicationKey {
        MemoryDeduplicationKey(
            literal: content,
            withoutGeneratedTimestamp: MemoryAutoTimestamp.strippingGeneratedLine(from: content)
        )
    }

    /// Whether `entry` already holds this durable fact.
    ///
    /// Literal equality always wins. The relaxed comparison is reached only for
    /// a write that generated its own stamp, and it drops the stored entry's
    /// leading stamp only when its persisted provenance says the tool generated
    /// it. This prevents an author-supplied, machine-shaped timestamp from
    /// being mistaken for tool metadata after a process restart.
    func matches(_ entry: GraphEntry) -> Bool {
        if entry.content.localizedCaseInsensitiveCompare(literal) == .orderedSame {
            return true
        }
        guard let withoutGeneratedTimestamp else { return false }
        guard entry.autoGeneratedTimestamp,
              let storedFact = MemoryAutoTimestamp.strippingGeneratedLine(from: entry.content) else {
            return false
        }
        return storedFact
            .localizedCaseInsensitiveCompare(withoutGeneratedTimestamp) == .orderedSame
    }
}
