//
//  BrowserArtifacts.swift
//  BrowserToolsFeature
//
//  Durable, bounded Browser artefacts such as screenshots.
//

import Crypto
import Foundation

#if canImport(Darwin)
import Darwin
#elseif canImport(Glibc)
import Glibc
#endif

enum BrowserArtifactError: LocalizedError {
    case emptyArtifact(String)
    case invalidPNGArtifact
    case artifactPathMustBeAbsolute
    case artifactOutsideOwnedDirectory
    case artifactIsNotRegularFile
    case artifactIsNotPNG
    case artifactTooLarge(Int)

    var errorDescription: String? {
        switch self {
        case let .emptyArtifact(kind):
            "Chrome returned an empty \(kind) artifact."
        case .invalidPNGArtifact:
            "Browser artifact is not a valid PNG header."
        case .artifactPathMustBeAbsolute:
            "Browser screenshot artifact paths must be absolute."
        case .artifactOutsideOwnedDirectory:
            "Browser can compare only screenshot artifacts it owns."
        case .artifactIsNotRegularFile:
            "Browser screenshot artifact is not a regular file."
        case .artifactIsNotPNG:
            "Browser can compare only PNG screenshot artifacts."
        case let .artifactTooLarge(maximumBytes):
            "Browser screenshot artifact exceeds the \(maximumBytes)-byte comparison limit."
        }
    }
}

struct BrowserArtifact: Codable, Hashable, Sendable {
    let path: String
    let mimeType: String
    let sizeBytes: Int
    let sha256: String
    let pixelWidth: Int?
    let pixelHeight: Int?
}

struct BrowserPNGDimensions: Codable, Hashable, Sendable {
    let width: Int
    let height: Int
}

/// A bounded PNG-header parser is sufficient for Browser-produced screenshots:
/// it exposes dimensions without decoding image content or invoking an external
/// image utility. It intentionally does not claim that arbitrary PNG bytes are
/// fully decoded or safe to render.
enum BrowserPNGHeader {
    private static let signature: [UInt8] = [137, 80, 78, 71, 13, 10, 26, 10]

    static func dimensions(in data: Data) -> BrowserPNGDimensions? {
        let bytes = Array(data.prefix(24))
        guard bytes.count == 24,
              Array(bytes[0..<8]) == signature,
              Array(bytes[12..<16]) == [73, 72, 68, 82]
        else {
            return nil
        }
        let width = integer(bytes[16..<20])
        let height = integer(bytes[20..<24])
        guard width > 0, height > 0 else { return nil }
        return BrowserPNGDimensions(width: width, height: height)
    }

    private static func integer(_ bytes: ArraySlice<UInt8>) -> Int {
        bytes.reduce(0) { partial, byte in
            (partial << 8) | Int(byte)
        }
    }
}

struct BrowserScreenshotOutput: Codable, Sendable {
    let page: BrowserPage
    let artifact: BrowserArtifact
    let fullPage: Bool
    let note: String

    init(page: BrowserPage, artifact: BrowserArtifact, fullPage: Bool) {
        self.page = page
        self.artifact = artifact
        self.fullPage = fullPage
        self.note = "The PNG is stored as a Browser artifact and is not embedded in the model transcript."
    }
}

struct BrowserOwnedScreenshot: Sendable {
    let artifact: BrowserArtifact
    let data: Data
}

/// Owns Browser-produced files only. Tool callers cannot choose a destination,
/// so a page cannot turn screenshots into arbitrary filesystem writes.
struct BrowserArtifactStore: Sendable {
    static let defaultMaximumArtifactCount = 50
    static let defaultRetentionAge: TimeInterval = 7 * 24 * 60 * 60
    static let maximumComparableScreenshotBytes = 20 * 1024 * 1024

    let rootDirectory: URL
    let maximumArtifactCount: Int
    let retentionAge: TimeInterval

    init(
        environment: [String: String] = ProcessInfo.processInfo.environment,
        maximumArtifactCount: Int = BrowserArtifactStore.defaultMaximumArtifactCount,
        retentionAge: TimeInterval = BrowserArtifactStore.defaultRetentionAge
    ) {
        self.init(
            rootDirectory: ChromeBrowserConfiguration(environment: environment)
                .profileDirectory
                .appendingPathComponent("artifacts", isDirectory: true),
            maximumArtifactCount: maximumArtifactCount,
            retentionAge: retentionAge
        )
    }

    init(
        rootDirectory: URL,
        maximumArtifactCount: Int = BrowserArtifactStore.defaultMaximumArtifactCount,
        retentionAge: TimeInterval = BrowserArtifactStore.defaultRetentionAge
    ) {
        self.rootDirectory = rootDirectory.standardizedFileURL
        self.maximumArtifactCount = max(maximumArtifactCount, 1)
        self.retentionAge = max(retentionAge, 0)
    }

    func storeScreenshotPNG(_ data: Data, pageID: String) throws -> BrowserArtifact {
        try store(
            data,
            pageID: pageID,
            prefix: "screenshot",
            fileExtension: "png",
            mimeType: "image/png"
        )
    }

    /// Stores only a PNG generated by the Browser visual-comparison pipeline.
    /// The caller cannot select the destination, preserving the same owned-path
    /// boundary used for screenshots supplied to the comparison tool.
    func storeVisualDiffPNG(_ data: Data) throws -> BrowserArtifact {
        guard data.count <= BrowserPNGCodec.maximumEncodedBytes else {
            throw BrowserArtifactError.artifactTooLarge(BrowserPNGCodec.maximumEncodedBytes)
        }
        return try store(
            data,
            pageID: "visual-diff",
            prefix: "diff",
            fileExtension: "png",
            mimeType: "image/png"
        )
    }

    func storePDF(_ data: Data, pageID: String) throws -> BrowserArtifact {
        try store(
            data,
            pageID: pageID,
            prefix: "page",
            fileExtension: "pdf",
            mimeType: "application/pdf"
        )
    }

    private func store(
        _ data: Data,
        pageID: String,
        prefix: String,
        fileExtension: String,
        mimeType: String
    ) throws -> BrowserArtifact {
        guard !data.isEmpty else { throw BrowserArtifactError.emptyArtifact(prefix) }
        try prepareDirectory()

        let filename = "\(prefix)-\(safePagePrefix(pageID))-\(UUID().uuidString.lowercased()).\(fileExtension)"
        let destination = rootDirectory.appendingPathComponent(filename, isDirectory: false)
        try data.write(to: destination, options: .atomic)
        try setPermissions(0o600, at: destination)
        try pruneRetainedArtifacts(preserving: destination)

        return makeArtifact(
            path: destination.path,
            mimeType: mimeType,
            data: data
        )
    }

    /// Loads a screenshot only after proving that it remains inside Browser's
    /// owned artifact directory. The public comparison tool accepts paths from
    /// the model, so this check is the boundary that prevents arbitrary file
    /// reads through an otherwise harmless visual-diff request.
    func loadOwnedScreenshot(
        at rawPath: String,
        maximumBytes: Int = BrowserArtifactStore.maximumComparableScreenshotBytes
    ) throws -> BrowserOwnedScreenshot {
        guard rawPath.hasPrefix("/") else {
            throw BrowserArtifactError.artifactPathMustBeAbsolute
        }
        let root = rootDirectory
            .resolvingSymlinksInPath()
            .standardizedFileURL
        let candidate = URL(fileURLWithPath: rawPath)
            .resolvingSymlinksInPath()
            .standardizedFileURL
        guard candidate.path.hasPrefix(root.path + "/") else {
            throw BrowserArtifactError.artifactOutsideOwnedDirectory
        }
        guard candidate.pathExtension.lowercased() == "png" else {
            throw BrowserArtifactError.artifactIsNotPNG
        }
        let values = try candidate.resourceValues(forKeys: [.isRegularFileKey, .fileSizeKey])
        guard values.isRegularFile == true else {
            throw BrowserArtifactError.artifactIsNotRegularFile
        }
        let maximumBytes = max(maximumBytes, 1)
        guard (values.fileSize ?? 0) <= maximumBytes else {
            throw BrowserArtifactError.artifactTooLarge(maximumBytes)
        }
        let data = try Data(contentsOf: candidate, options: [.mappedIfSafe])
        guard !data.isEmpty,
              data.count <= maximumBytes
        else {
            throw BrowserArtifactError.artifactTooLarge(maximumBytes)
        }
        guard BrowserPNGHeader.dimensions(in: data) != nil else {
            throw BrowserArtifactError.invalidPNGArtifact
        }
        return BrowserOwnedScreenshot(
            artifact: makeArtifact(path: candidate.path, mimeType: "image/png", data: data),
            data: data
        )
    }

    private func makeArtifact(path: String, mimeType: String, data: Data) -> BrowserArtifact {
        let dimensions = mimeType == "image/png" ? BrowserPNGHeader.dimensions(in: data) : nil
        return BrowserArtifact(
            path: path,
            mimeType: mimeType,
            sizeBytes: data.count,
            sha256: Self.sha256Hex(data),
            pixelWidth: dimensions?.width,
            pixelHeight: dimensions?.height
        )
    }

    private static func sha256Hex(_ data: Data) -> String {
        SHA256.hash(data: data)
            .map { String(format: "%02x", $0) }
            .joined()
    }

    private func prepareDirectory() throws {
        let fileManager = FileManager.default
        try fileManager.createDirectory(
            at: rootDirectory,
            withIntermediateDirectories: true
        )
        try setPermissions(0o700, at: rootDirectory)
    }

    private func pruneRetainedArtifacts(
        now: Date = Date(),
        preserving preservedURL: URL? = nil
    ) throws {
        let fileManager = FileManager.default
        let resourceKeys: Set<URLResourceKey> = [
            .contentModificationDateKey,
            .creationDateKey,
            .isRegularFileKey,
        ]
        let contents = try fileManager.contentsOfDirectory(
            at: rootDirectory,
            includingPropertiesForKeys: Array(resourceKeys),
            options: [.skipsHiddenFiles]
        )
        var retained: [(url: URL, date: Date)] = []

        for url in contents where ["pdf", "png"].contains(url.pathExtension.lowercased()) {
            let values = try? url.resourceValues(forKeys: resourceKeys)
            guard values?.isRegularFile != false else { continue }
            let date = values?.contentModificationDate ?? values?.creationDate ?? .distantPast
            if url == preservedURL {
                retained.append((url, date))
            } else if now.timeIntervalSince(date) > retentionAge {
                try? fileManager.removeItem(at: url)
            } else {
                retained.append((url, date))
            }
        }

        retained.sort { lhs, rhs in
            if lhs.url == preservedURL { return true }
            if rhs.url == preservedURL { return false }
            return lhs.date > rhs.date
        }
        guard retained.count > maximumArtifactCount else { return }
        for artifact in retained.dropFirst(maximumArtifactCount) {
            try? fileManager.removeItem(at: artifact.url)
        }
    }

    private func safePagePrefix(_ pageID: String) -> String {
        let safeScalars = pageID.unicodeScalars.filter { scalar in
            CharacterSet.alphanumerics.contains(scalar)
        }
        let prefix = String(String.UnicodeScalarView(safeScalars)).prefix(12)
        return prefix.isEmpty ? "page" : String(prefix)
    }

    private func setPermissions(_ permissions: Int, at url: URL) throws {
        #if canImport(Darwin) || canImport(Glibc)
        try FileManager.default.setAttributes(
            [.posixPermissions: permissions],
            ofItemAtPath: url.path
        )
        #endif
    }
}
