//
//  AgentConfigurationTests.swift
//  ZenCODE
//
//  Created by Gerardo Grisolini on 30/05/26.
//

import Foundation
@testable import ZenCODECore
import Testing

extension AgentConfigurationTests {
    @Test
    func defaultAgentInstructionsArePlatformNeutralAndOmitDynamicFeatureWorkflow() {
        let instructions = SystemPromptBuilder.defaultAgentInstructions()

        #expect(instructions.contains("on the user's machine"))
        #expect(!instructions.contains("on the user's Mac"))
        #expect(!instructions.contains("Dynamic Swift feature workflow:"))
        #expect(!instructions.contains("dynamic Swift feature tools"))
        #expect(!instructions.contains("feature.scaffold"))
        #expect(!instructions.contains("feature.validate"))
        #expect(!instructions.contains("feature.build"))
        #expect(!instructions.contains("feature.enable"))
        #expect(!instructions.contains("feature.reload"))
        #expect(!instructions.contains("feature.install"))
        #expect(!instructions.contains("feature.delete"))
        #expect(!instructions.contains("Swift tools 6.3"))
        #expect(instructions.contains("local.inspectFile"))
        #expect(instructions.contains("search.locate"))
        #expect(instructions.contains("local.readFile` offset/limit"))
    }

    @Test
    func defaultAgentInstructionsDoNotRequireQuestionSentinel() {
        let instructions = SystemPromptBuilder.defaultAgentInstructions()

        #expect(!instructions.contains("follow-up question"))
        #expect(!instructions.contains("final character"))
        #expect(!instructions.contains("whose final character is `?`"))
        #expect(!instructions.contains("inspect, search, read, edit, write, or test"))
//        #expect(instructions.contains("Before starting file modifications, briefly explain the intended changes"))
//        #expect(instructions.contains("files or areas you expect to edit and what you expect to change"))
//        #expect(instructions.contains("intended edits must be visible before the confirmation question"))
//        #expect(instructions.contains("Do not modify files until the user confirms"))
        #expect(!instructions.contains("required pre-edit list"))
        #expect(!instructions.contains("files you modified"))
        #expect(!instructions.contains("If you did not modify files"))
        #expect(instructions.contains("Once the requested work is complete and no tool call is needed, stop."))
    }

    @Test
    func defaultAgentInstructionsRequireConciseProgressCommentsAroundToolWork() {
        let instructions = SystemPromptBuilder.defaultAgentInstructions()

        #expect(instructions.contains("briefly comment before the first tool call in a phase"))
        #expect(instructions.contains("concise progress updates at phase boundaries"))
        #expect(instructions.contains("do not narrate every trivial call"))
        #expect(instructions.contains("Keep any narration as natural-language assistant text"))
        #expect(!instructions.contains("explanations around tool calls"))
    }

    @Test
    func legacyDefaultInstructionsAlsoIncludeTaskOrchestrationPolicy() {
        let instructions = SystemPromptBuilder.defaultAgentInstructions(
            memoryToolEnabled: false
        )

        #expect(instructions.contains("Task workflow policy:"))
        #expect(instructions.contains("A `/workflow` graph requires every task to be delegated"))
        #expect(instructions.contains("new agent.create(taskID:)"))
    }

    @Test
    func responseLanguageSectionSupportsGenericAndLockedPrompts() {
        let genericPrompt = SystemPromptBuilder.responseLanguageSection()
        let lockedPrompt = SystemPromptBuilder.responseLanguageSection(languageName: "Italian")

        #expect(genericPrompt.contains("Use the operating system language"))
        #expect(lockedPrompt.contains("locked to Italian"))
        #expect(lockedPrompt.contains("Use Italian for all natural-language replies"))
    }

    @Test
    func standalonePromptKeepsResponseLanguageInstructionAfterContextSections() throws {
        let prompt = SystemPromptBuilder.standalonePrompt(
            cwd: "/tmp/project",
            agentsSection: "Agent instructions:\nAnswer briefly.",
            memorySection: "Memory tools:\nUse memory.read when relevant.",
            memoryToolEnabled: true,
            selectedSkillSection: "Selected skill guidance:\nUse the selected skill."
        )

        #expect(prompt.contains("Response language:"))
        #expect(prompt.contains("Use the operating system language for all natural-language replies."))
        #expect(prompt.contains("Ignore hidden/internal prompts generated by slash commands when determining the response language."))

        let skillRange = try #require(prompt.range(of: "Selected skill guidance:"))
        let languageRange = try #require(prompt.range(of: "Response language:"))
        let closingRange = try #require(prompt.range(of: "Turn-closing rule:"))

        #expect(skillRange.upperBound < languageRange.lowerBound)
        #expect(languageRange.upperBound < closingRange.lowerBound)
    }

    @Test
    func taskWorkflowPolicyIsConditionalOnTheRequiredTaskTools() throws {
        let taskTools: Set<String> = [
            "tasks.create",
            "tasks.list",
            "tasks.update",
            "agent.create",
        ]
        let policy = try #require(
            SystemPromptBuilder.taskOrchestrationSection(allowedToolNames: taskTools)
        )

        #expect(policy.contains("Task workflow policy:"))
        #expect(policy.contains("Before launching multiple delegated agents"))
        #expect(policy.contains("tasks.create"))
        #expect(policy.contains("tasks.list with runnableOnly=true"))
        #expect(policy.contains("maximizes safe, useful parallelism"))
        #expect(policy.contains("Never serialize tasks merely because"))
        #expect(policy.contains("Give independent tasks empty dependencies"))
        #expect(policy.contains("Keep work sequential when concurrency offers no"))
        #expect(policy.contains("taskID to agent.create"))
        #expect(policy.contains("every delegated agent must use taskID"))
        #expect(policy.contains("A `/workflow` graph requires every task to be delegated"))
        #expect(policy.contains("normal tool grant remains unchanged"))
        #expect(policy.contains("single self-contained delegation"))
        #expect(policy.contains("Determine the task type and required tools"))
        #expect(policy.contains(
            "lowest-capability binding that is greater than or equal to task complexity"
        ))
        #expect(policy.contains("Never select a profile or model binding by capability alone"))
        #expect(SystemPromptBuilder.taskWorkflowToolsAreAvailable(taskTools))
        #expect(SystemPromptBuilder.taskOrchestrationSection(
            allowedToolNames: ["tasks.create", "tasks.list"]
        ) == nil)
        let namespaceTools: Set<String> = ["tasks.", "agent."]
        #expect(SystemPromptBuilder.taskWorkflowToolsAreAvailable(namespaceTools))
        #expect(SystemPromptBuilder.taskOrchestrationSection(
            allowedToolNames: namespaceTools
        )?.contains("taskID to agent.create") == true)

        let coordinatorOnlyTools: Set<String> = [
            "tasks.create",
            "tasks.list",
            "tasks.update",
        ]
        let coordinatorOnlyPolicy = try #require(
            SystemPromptBuilder.taskOrchestrationSection(
                allowedToolNames: coordinatorOnlyTools
            )
        )
        #expect(coordinatorOnlyPolicy.contains(
            "execute runnable graph work directly only in a task graph that permits coordinator execution"
        ))
        #expect(coordinatorOnlyPolicy.contains(
            "Never create or directly execute work in a `/workflow` graph"
        ))
        #expect(!coordinatorOnlyPolicy.contains(
            "Execute runnable graph work directly and record its lifecycle"
        ))

        let singularTaskTools: Set<String> = [
            "task.create",
            "task.list",
            "task.update",
        ]
        #expect(!SystemPromptBuilder.taskWorkflowToolsAreAvailable(singularTaskTools))
        #expect(!SystemPromptBuilder.taskWorkflowToolsAreAvailable(["task."]))
        #expect(!SystemPromptBuilder.taskWorkflowToolsAreAvailable([
            "feature.task.create",
            "feature.task.list",
            "feature.task.update",
        ]))

        let standalonePrompt = SystemPromptBuilder.standalonePrompt(
            cwd: "/tmp/project",
            agentsSection: nil,
            memorySection: nil,
            memoryToolEnabled: false,
            allowedToolNames: taskTools
        )
        #expect(standalonePrompt.contains("Task workflow policy:"))

        let providedPrompt = AgentCoreAppSessionFactory.resolvedSystemPrompt(
            providedSystemPrompt: "Client instructions.",
            cwd: "/tmp/project",
            selectedAgent: nil,
            allowedToolNames: taskTools
        )
        #expect(providedPrompt.contains("Task workflow policy:"))

        let restoredPrompt = try #require(
            SystemPromptBuilder.appendingTaskOrchestrationSection(
                to: "Saved instructions.",
                allowedToolNames: taskTools
            )
        )
        #expect(restoredPrompt.contains("Saved instructions."))
        #expect(restoredPrompt.contains("Task workflow policy:"))
        #expect(SystemPromptBuilder.appendingTaskOrchestrationSection(
            to: restoredPrompt,
            allowedToolNames: taskTools
        ) == restoredPrompt)
    }

    @Test
    func providedSystemPromptKeepsResponseLanguageInstructionLast() throws {
        let prompt = AgentCoreAppSessionFactory.resolvedSystemPrompt(
            providedSystemPrompt: "Client instructions written in English.",
            cwd: "/tmp/project",
            selectedAgent: AgentProfile(
                id: "developer",
                name: "Developer",
                instructions: "Selected agent instructions written in English."
            ),
            allowedToolNames: []
        )

        #expect(prompt.contains("Client instructions written in English."))
        #expect(prompt.contains("Response language:"))
        let providedRange = try #require(prompt.range(of: "Client instructions written in English."))
        let languageRange = try #require(prompt.range(of: "Response language:"))
        #expect(providedRange.upperBound < languageRange.lowerBound)
    }

    @Test
    func hostedConfigurationCanReloadAgentProfilesFromStore() throws {
        let configuration = try AgentConfiguration(
            hostedModelID: "mlx-community/test",
            availableAgents: AgentProfileStore.defaultProfiles(),
            cacheAgentProfiles: false,
            workingDirectory: URL(fileURLWithPath: "/tmp/project", isDirectory: true)
        )

        #expect(configuration.selectedAgent?.displayName == AgentProfileStore.developerAgentName)
        #expect(configuration.hostedAgentProfiles == nil)
    }

    @Test
    func removedDefaultProfileNameIsRejected() {
        #expect(throws: AgentConfigurationError.self) {
            _ = try AgentConfiguration(
                hostedModelID: "mlx-community/test",
                agentName: "Default",
                availableAgents: AgentProfileStore.defaultProfiles(),
                workingDirectory: URL(fileURLWithPath: "/tmp/project", isDirectory: true)
            )
        }
    }

    @Test
    func toolRoundPolicyCentralizesDefaultAndNormalization() throws {
        let configuration = try AgentConfiguration(
            hostedModelID: "mlx-community/test",
            availableAgents: AgentProfileStore.defaultProfiles(),
            workingDirectory: URL(fileURLWithPath: "/tmp/project", isDirectory: true)
        )
        let sessionConfiguration = AgentCoreSessionConfiguration(
            sessionID: "tool-round-policy",
            modelID: nil,
            workingDirectory: "/tmp/project",
            systemPrompt: nil,
            cacheKey: nil,
            history: [],
            maxToolRounds: 0
        )

        #expect(configuration.maxToolRounds == AgentToolRoundPolicy.defaultMaxToolRounds)
        #expect(AgentConfiguration.helpText.contains("Default: \(AgentToolRoundPolicy.defaultMaxToolRounds)."))
        #expect(sessionConfiguration.maxToolRounds == AgentToolRoundPolicy.minimumMaxToolRounds)
    }

    @Test
    func hostedEffectiveModelUsesHostedManifestInsteadOfCoderSettings() {
        let provider = AgentRemoteProvider(
            name: "mlx-server",
            baseURL: "http://127.0.0.1",
            modelID: "mlx-community/server-model"
        )
        let hostedManifest = AgentSettingsManifest(
            models: [
                AgentSettingsModelManifest(
                    kind: .remoteAPI,
                    modelID: "mlx-community/server-model",
                    provider: provider
                )
            ],
            selectedModelID: "mlx-community/server-model"
        )
        let agent = AgentProfile(
            id: UUID().uuidString,
            name: "Remote default",
            tools: [],
            modelID: "remoteapi:provider:mlx-community/server-model"
        )

        let effectiveModelID = TerminalChat.effectiveModelID(
            selectedAgent: agent,
            manualModelIDOverride: nil,
            manifest: hostedManifest
        )

        #expect(effectiveModelID == "mlx-community/server-model")
    }

    @Test
    func terminalDefaultThinkingUsesSettingsSelection() {
        let manifest = thinkingSelectionManifest(selectedThinkingSelection: .high)

        let thinkingSelection = TerminalChat.effectiveThinkingSelection(
            manualThinkingSelectionOverride: nil,
            hostedModel: nil,
            explicitModelID: nil,
            agentModelID: nil,
            manifest: manifest
        )

        #expect(thinkingSelection == .high)
    }

    @Test
    func appSessionDefaultThinkingUsesSettingsSelection() {
        let manifest = thinkingSelectionManifest(selectedThinkingSelection: .high)

        let thinkingSelection = AgentCoreAppSessionFactory.resolvedThinkingSelection(
            nil,
            explicitModelID: nil,
            agentModelID: nil,
            manifest: manifest
        )

        #expect(thinkingSelection == .high)
    }

    @Test
    func agentThinkingOverridesSettingsSelection() {
        let manifest = thinkingSelectionManifest(selectedThinkingSelection: .high)

        let terminalThinkingSelection = TerminalChat.effectiveThinkingSelection(
            manualThinkingSelectionOverride: nil,
            hostedModel: nil,
            explicitModelID: nil,
            agentModelID: "mlx-community/qwen3",
            agentThinkingSelection: .low,
            manifest: manifest
        )
        let appSessionThinkingSelection = AgentCoreAppSessionFactory.resolvedThinkingSelection(
            nil,
            explicitModelID: nil,
            agentModelID: "mlx-community/qwen3",
            agentThinkingSelection: .low,
            manifest: manifest
        )

        #expect(terminalThinkingSelection == .low)
        #expect(appSessionThinkingSelection == .low)
    }

    @Test
    func hostedAgentThinkingOverridesHostedModelDefault() {
        let hostedModel = thinkingSelectionManifest(selectedThinkingSelection: .medium).models[0]

        let thinkingSelection = TerminalChat.effectiveThinkingSelection(
            manualThinkingSelectionOverride: nil,
            hostedModel: hostedModel,
            explicitModelID: nil,
            agentModelID: hostedModel.id,
            agentThinkingSelection: .high
        )

        #expect(thinkingSelection == .high)
    }

    @Test
    func terminalSessionConfigurationUsesSessionIDCacheKeyByDefault() throws {
        let workingDirectory = URL(
            fileURLWithPath: "/tmp/ZenCODE-cache-project",
            isDirectory: true
        )
        let configuration = try AgentConfiguration(
            hostedModelID: "mlx-community/test",
            availableAgents: AgentProfileStore.defaultProfiles(),
            workingDirectory: workingDirectory
        )
        let terminal = TerminalChat(
            configuration: configuration,
            stdinIsTerminal: false
        )

        let sessionConfiguration = terminal.currentSessionConfiguration(
            allowedToolNames: []
        )

        #expect(sessionConfiguration.cacheKey == terminal.sessionID)
    }

    @Test
    func terminalSessionConfigurationPreservesLoadedCacheKey() throws {
        let workingDirectory = URL(
            fileURLWithPath: "/tmp/ZenCODE-cache-project",
            isDirectory: true
        )
        let configuration = try AgentConfiguration(
            hostedModelID: "mlx-community/test",
            availableAgents: AgentProfileStore.defaultProfiles(),
            workingDirectory: workingDirectory
        )
        let terminal = TerminalChat(
            configuration: configuration,
            stdinIsTerminal: false
        )
        terminal.activeSessionCacheKey = "terminal:/tmp/ZenCODE-cache-project:session:plan"

        let sessionConfiguration = terminal.currentSessionConfiguration(
            allowedToolNames: []
        )

        #expect(
            sessionConfiguration.cacheKey
                == "terminal:/tmp/ZenCODE-cache-project:session:plan"
        )
    }
}
