//
//  SwiftFeatureRuntimeTests.swift
//  ZenCODE
//
//  Created by Gerardo Grisolini on 30/05/26.
//

import Foundation
@testable import ZenCODECore
import Testing
import ToolCore

extension SwiftFeatureRuntimeTests {
    @Test
    func processRunnerWritesStandardInput() async throws {
        let result = try await AsyncProcessRunner.run(
            executableURL: URL(fileURLWithPath: "/bin/cat"),
            arguments: [],
            stdinData: Data("hello feature\n".utf8),
            timeout: 10
        )

        #expect(result.exitCode == 0)
        #expect(result.stdout == "hello feature\n")
    }

    @Test
    func registryDiscoversExecutableManifest() throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("swift-feature-registry-\(UUID().uuidString)", isDirectory: true)
        let featureURL = rootURL.appendingPathComponent("example", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }

        try FileManager.default.createDirectory(
            at: featureURL,
            withIntermediateDirectories: true
        )
        let executableURL = featureURL.appendingPathComponent("feature")
        try "#!/bin/sh\n".write(to: executableURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )
        try """
        {
          "id": "example",
          "enabled": true,
          "executable": "feature",
          "supports_persistent_session": true,
          "tools": [
            {
              "name": "feature.example.echo",
              "description": "Echo test",
              "inputSchema": {
                "type": "object",
                "properties": {
                  "text": { "type": "string" }
                },
                "required": ["text"]
              },
              "presentation": {
                "title": "Echo",
                "action": "Echo",
                "kind": "execute",
                "metadata": [],
                "sections": []
              }
            }
          ]
        }
        """.write(
            to: featureURL.appendingPathComponent(SwiftFeatureRegistry.manifestFilename),
            atomically: true,
            encoding: .utf8
        )

        let bundles = SwiftFeatureRegistry.discoverFeatureBundles(
            searchRoots: [rootURL]
        )

        #expect(bundles.count == 1)
        #expect(bundles.first?.id == "example")
        #expect(bundles.first?.supportsPersistentSession == true)
        #expect(bundles.first?.tools.first?.name == "feature.example.echo")
        #expect(bundles.first?.tools.first?.requiredInputArgumentNames() == ["text"])
    }

    @Test
    func registrySupportsGeneratedFeaturePackageManifestSchema() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("swift-feature-schema-\(UUID().uuidString)", isDirectory: true)
        let featureURL = rootURL.appendingPathComponent("rich", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }

        try FileManager.default.createDirectory(
            at: featureURL,
            withIntermediateDirectories: true
        )
        let executableURL = featureURL.appendingPathComponent("feature")
        try """
        #!/bin/sh
        if [ "$1" = "--list-tools" ]; then
          printf '{"tools":[{"name":"custom.dynamic","description":"Dynamic custom tool","inputSchema":"{}","presentation":{"title":"Dynamic tool","action":"Use","kind":"other","metadata":[],"sections":[]}}]}\n'
          exit 0
        fi
        cat >/dev/null
        printf '{"ok":true,"output":"custom-output"}\n'
        """.write(to: executableURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )
        try """
        {
          "schemaVersion": 1,
          "id": "custom-feature",
          "displayName": "Custom Feature",
          "description": "Feature generated by an agent.",
          "enabled": true,
          "executable": "feature",
          "discoversToolsAtRuntime": true,
          "invocationTimeoutSeconds": 240,
          "toolNamePrefixes": ["custom."],
          "toolNameAliases": ["CustomDynamic"],
          "build": {
            "system": "swiftpm",
            "packagePath": ".",
            "product": "custom-feature",
            "configuration": "release",
            "executablePath": ".build/release/custom-feature"
          },
          "generated": {
            "by": "ZenCODE",
            "prompt": "Need a custom feature",
            "createdAt": "2026-05-30T12:00:00Z"
          },
          "tools": []
        }
        """.write(
            to: featureURL.appendingPathComponent(SwiftFeatureRegistry.manifestFilename),
            atomically: true,
            encoding: .utf8
        )

        let bundles = SwiftFeatureRegistry.discoverFeatureBundles(
            searchRoots: [rootURL]
        )
        #expect(bundles.first?.id == "custom-feature")
        #expect(bundles.first?.toolNamePrefixes == ["custom."])
        #expect(bundles.first?.toolNameAliases == ["CustomDynamic"])
        #expect(bundles.first?.discoversToolsAtRuntime == true)
        #expect(bundles.first?.invocationTimeoutSeconds == 240)

        let runtime = SwiftFeatureRuntime(featureSearchRoots: [rootURL])
        let statuses = await runtime.featureStatuses()
        let status = try #require(statuses.first { $0.id == "custom-feature" })
        #expect(status.displayName == "Custom Feature")
        #expect(status.description == "Feature generated by an agent.")
        #expect(status.build?.product == "custom-feature")
        #expect(status.generated?.by == "ZenCODE")
        #expect(status.enabled && status.available && status.editable && !status.adoptable)
        #expect(status.source == .generated && !status.isCore)
        #expect(status.executablePath == executableURL.path)
        #expect(status.manifestPath == featureURL.appendingPathComponent(SwiftFeatureRegistry.manifestFilename).path)
        #expect(status.toolNamePrefixes == ["custom."] && status.toolNameAliases == ["CustomDynamic"])

        let descriptors = await runtime.descriptors(
            allowedToolNames: ["custom."]
        )
        #expect(descriptors.map(\.name) == ["custom.dynamic"])
        try SwiftFeatureRegistry.setFeatureManifestEnabled(
            manifestURL: featureURL.appendingPathComponent(SwiftFeatureRegistry.manifestFilename), enabled: false
        )
        #expect(SwiftFeatureRegistry.discoverFeatureBundles(searchRoots: [rootURL]).isEmpty)
        let disabled = try #require(SwiftFeatureRuntime.defaultFeatureStatuses(searchRoots: [rootURL], includeTools: false)
            .first { $0.id == "custom-feature" })
        #expect(!disabled.enabled && disabled.available && disabled.tools.isEmpty && disabled.toolCount == 0)
    }

    @Test(arguments: [SwiftFeatureBundleSource.generated, .bundled], [false, true])
    func bundleStatusPreservesOverrides(source: SwiftFeatureBundleSource, isCore: Bool) {
        let feature = SwiftFeatureBundle(
            id: "projection", executableURL: URL(fileURLWithPath: "/tmp/projection"), tools: [],
            toolNamePrefixes: ["z.", "a."], toolNameAliases: ["Z", "A"],
            discoversToolsAtRuntime: true, source: source, isCore: isCore
        )
        let status = SwiftFeatureRuntime.status(
            from: feature, enabled: false, available: true,
            manifestPath: "/tmp/custom.json", issue: "fixture", tools: ["z.tool", "a.tool", "z.tool"]
        )
        #expect(status.id == feature.id && status.source == source && status.isCore == isCore)
        #expect(status.editable == (source == .generated && !isCore))
        #expect(status.adoptable == (source == .bundled && !isCore))
        #expect(!status.enabled && status.available && status.issue == "fixture")
        #expect(status.executablePath == feature.executableURL.path && status.manifestPath == "/tmp/custom.json")
        #expect(status.tools == ["a.tool", "z.tool", "z.tool"] && status.toolCount == 3)
        #expect(status.toolNamePrefixes == ["z.", "a."] && status.toolNameAliases == ["Z", "A"])
        #expect(status.discoversToolsAtRuntime && status.displayName == nil && status.description == nil)
        #expect(status.adoptedFrom == nil && status.build == nil && status.generated == nil)
    }
}


extension SwiftFeatureRuntimeTests {
    @Test
    func persistentFeatureReusesOneProcessForDiscoveryAndInvocations() async throws {
        let fixture = try PersistentFeatureFixture()
        defer { fixture.remove() }

        let runtime = SwiftFeatureRuntime(features: [
            fixture.bundle(supportsPersistentSession: true)
        ])
        let descriptors = await runtime.descriptors(allowedToolNames: ["fixture."])
        #expect(descriptors.map(\.name) == ["fixture.echo"])

        let first = try #require(await runtime.executeIfAvailable(
            toolCall: DirectAgentToolCall(
                id: UUID().uuidString,
                name: "fixture.echo",
                argumentsObject: [:],
                argumentsJSON: "{}"
            ),
            workingDirectory: fixture.directoryURL
        ))
        let second = try #require(await runtime.executeIfAvailable(
            toolCall: DirectAgentToolCall(
                id: UUID().uuidString,
                name: "fixture.echo",
                argumentsObject: [:],
                argumentsJSON: "{}"
            ),
            workingDirectory: fixture.directoryURL
        ))
        #expect(first == "served")
        #expect(second == "served")

        let records = try fixture.processRecords()
        #expect(records.count == 1)
        #expect(records.first?.hasPrefix("serve:") == true)
        await runtime.shutdown()
    }

    @Test
    func nonPersistentFeatureRetainsOneShotProcessIsolation() async throws {
        let fixture = try PersistentFeatureFixture()
        defer { fixture.remove() }

        let runtime = SwiftFeatureRuntime(features: [
            fixture.bundle(supportsPersistentSession: false)
        ])
        let descriptors = await runtime.descriptors(allowedToolNames: ["fixture."])
        #expect(descriptors.map(\.name) == ["fixture.echo"])

        _ = try #require(await runtime.executeIfAvailable(
            toolCall: DirectAgentToolCall(
                id: UUID().uuidString,
                name: "fixture.echo",
                argumentsObject: [:],
                argumentsJSON: "{}"
            ),
            workingDirectory: fixture.directoryURL
        ))
        _ = try #require(await runtime.executeIfAvailable(
            toolCall: DirectAgentToolCall(
                id: UUID().uuidString,
                name: "fixture.echo",
                argumentsObject: [:],
                argumentsJSON: "{}"
            ),
            workingDirectory: fixture.directoryURL
        ))

        let records = try fixture.processRecords()
        #expect(records.count == 3)
        #expect(records.allSatisfy { $0.hasPrefix("single:") })
        await runtime.shutdown()
    }

    @Test
    func persistentFeatureDoesNotRestartAfterRuntimeShutdown() async throws {
        let fixture = try PersistentFeatureFixture()
        defer { fixture.remove() }

        let runtime = SwiftFeatureRuntime(features: [
            fixture.bundle(supportsPersistentSession: true)
        ])
        _ = await runtime.descriptors(allowedToolNames: ["fixture."])
        await runtime.shutdown()

        do {
            _ = try await runtime.executeIfAvailable(
                toolCall: DirectAgentToolCall(
                    id: UUID().uuidString,
                    name: "fixture.echo",
                    argumentsObject: [:],
                    argumentsJSON: "{}"
                ),
                workingDirectory: fixture.directoryURL
            )
            Issue.record("A shut down runtime must not start another persistent feature process.")
        } catch {
            // Terminal runtime shutdown intentionally rejects later persistent
            // requests instead of silently creating a new child.
        }

        #expect(try fixture.processRecords().filter { $0.hasPrefix("serve:") }.count == 1)
    }
}

private struct PersistentFeatureFixture {
    let directoryURL: URL
    private let executableURL: URL
    private let processLogURL: URL

    init(crashOnFirstInvocation: Bool = false) throws {
        directoryURL = FileManager.default.temporaryDirectory.appendingPathComponent(
            "zencode-persistent-feature-\(UUID().uuidString)",
            isDirectory: true
        )
        executableURL = directoryURL.appendingPathComponent("fixture-feature")
        processLogURL = directoryURL.appendingPathComponent("processes.log")
        try FileManager.default.createDirectory(at: directoryURL, withIntermediateDirectories: true)
        let crashMarkerURL = crashOnFirstInvocation
            ? directoryURL.appendingPathComponent("crash-once")
            : nil
        try Self.script(
            processLogURL: processLogURL,
            crashMarkerURL: crashMarkerURL
        ).write(
            to: executableURL,
            atomically: true,
            encoding: .utf8
        )
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )
    }

    func bundle(supportsPersistentSession: Bool) -> SwiftFeatureBundle {
        SwiftFeatureBundle(
            id: "persistent-fixture",
            executableURL: executableURL,
            tools: [],
            toolNamePrefixes: ["fixture."],
            discoversToolsAtRuntime: true,
            supportsPersistentSession: supportsPersistentSession
        )
    }

    func processRecords() throws -> [String] {
        try String(contentsOf: processLogURL, encoding: .utf8)
            .split(separator: "\n")
            .map(String.init)
    }

    func remove() {
        try? FileManager.default.removeItem(at: directoryURL)
    }

    private static func script(processLogURL: URL, crashMarkerURL: URL?) -> String {
        let listResponse = #"{"tools":[{"name":"fixture.echo","description":"Fixture echo","inputSchema":"{}","presentation":{"title":"Echo","action":"Echo","kind":"other","metadata":[],"sections":[]}}]}"#
        let invocationResponse = #"{"ok":true,"output":"served"}"#
        return """
        #!/bin/sh
        process_log='\(processLogURL.path)'
        crash_marker='\(crashMarkerURL?.path ?? "")'
        list_response=$(printf '%s' '\(listResponse)' | base64 | tr -d '\\n')
        invocation_response=$(printf '%s' '\(invocationResponse)' | base64 | tr -d '\\n')
        if [ "$1" = "--serve" ]; then
          printf 'serve:%s\\n' "$$" >> "$process_log"
          while IFS= read -r line; do
            request_id=$(printf '%s' "$line" | sed -n 's/.*"id":"\\([^"\\]*\\)".*/\\1/p')
            case "$line" in
              *'"operation":"listTools"'*)
                printf '{"id":"%s","responseData":"%s"}\\n' "$request_id" "$list_response"
                ;;
              *'"operation":"invoke"'*)
                if [ -n "$crash_marker" ] && [ ! -e "$crash_marker" ]; then
                  touch "$crash_marker"
                  exit 9
                fi
                printf '{"id":"%s","responseData":"%s"}\\n' "$request_id" "$invocation_response"
                ;;
              *'"operation":"shutdown"'*)
                printf '{"id":"%s","responseData":""}\\n' "$request_id"
                exit 0
                ;;
            esac
          done
          exit 0
        fi
        printf 'single:%s:%s\\n' "$1" "$$" >> "$process_log"
        if [ "$1" = "--list-tools" ]; then
          printf '%s\\n' '\(listResponse)'
          exit 0
        fi
        cat >/dev/null
        printf '%s\\n' '\(invocationResponse)'
        """
    }
}


extension SwiftFeatureRuntimeTests {
    @Test
    func persistentFeatureRestartsForTheNextRequestAfterChildExit() async throws {
        let fixture = try PersistentFeatureFixture(crashOnFirstInvocation: true)
        defer { fixture.remove() }

        let runtime = SwiftFeatureRuntime(features: [
            fixture.bundle(supportsPersistentSession: true)
        ])
        _ = await runtime.descriptors(allowedToolNames: ["fixture."])

        do {
            _ = try await runtime.executeIfAvailable(
                toolCall: DirectAgentToolCall(
                    id: UUID().uuidString,
                    name: "fixture.echo",
                    argumentsObject: [:],
                    argumentsJSON: "{}"
                ),
                workingDirectory: fixture.directoryURL
            )
            Issue.record("The first invocation should observe the fixture child exit.")
        } catch {
            // A request whose child dies has no exactly-once guarantee, so it is
            // deliberately surfaced rather than replayed. The next request gets
            // a clean process.
        }

        let output = try #require(await runtime.executeIfAvailable(
            toolCall: DirectAgentToolCall(
                id: UUID().uuidString,
                name: "fixture.echo",
                argumentsObject: [:],
                argumentsJSON: "{}"
            ),
            workingDirectory: fixture.directoryURL
        ))
        #expect(output == "served")
        #expect(try fixture.processRecords().filter { $0.hasPrefix("serve:") }.count == 2)
        await runtime.shutdown()
    }
}
