import Foundation

enum GenerateFeatureCatalog {
    struct Catalog: Codable { let schemaVersion: Int; let features: [Feature] }
    struct Feature: Codable {
        let id: String
        let productName: String
        let sourceRelativePath: String
        let isInstalledOnLinux: Bool
        let description: String?
        let toolNamePrefixes: [String]?
        let toolNameAliases: [String]?
        let discoversToolsAtRuntime: Bool?
        let supportsPersistentSession: Bool?
        let invocationTimeoutSeconds: Double?
    }

    static func run() throws {
        let check = CommandLine.arguments.dropFirst() == ["--check"]
        let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath, isDirectory: true)
        let featuresRoot = root.appendingPathComponent("Sources/Features", isDirectory: true)
        let packageURLs = try FileManager.default.contentsOfDirectory(
            at: featuresRoot,
            includingPropertiesForKeys: [.isDirectoryKey],
            options: [.skipsHiddenFiles]
        ).filter { (try? $0.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true }

        var features: [Feature] = []
        for packageURL in packageURLs {
            let manifestURL = packageURL.appendingPathComponent("feature-distribution.json")
            guard FileManager.default.fileExists(atPath: manifestURL.path) else {
                throw GeneratorError("missing per-package manifest: \(manifestURL.path)")
            }
            let feature = try JSONDecoder().decode(Feature.self, from: Data(contentsOf: manifestURL))
            let expectedPath = packageURL.path.replacingOccurrences(of: root.path + "/", with: "")
            guard feature.sourceRelativePath == expectedPath else {
                throw GeneratorError("sourceRelativePath mismatch for \(feature.id)")
            }
            features.append(feature)
        }
        features.sort { $0.id < $1.id }
        let duplicateIDs = Dictionary(grouping: features, by: \.id).filter { $0.value.count > 1 }.keys.sorted()
        guard duplicateIDs.isEmpty else {
            throw GeneratorError("duplicate feature ids: \(duplicateIDs.joined(separator: ", "))")
        }
        let duplicateProducts = Dictionary(grouping: features, by: \.productName).filter { $0.value.count > 1 }.keys.sorted()
        guard duplicateProducts.isEmpty else {
            throw GeneratorError("duplicate feature products: \(duplicateProducts.joined(separator: ", "))")
        }

        let encoder = JSONEncoder()
        let featureObjects = try features.map { feature -> [String: Any] in
            let data = try encoder.encode(feature)
            guard let object = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
                throw GeneratorError("could not encode feature \(feature.id)")
            }
            return object
        }
        var catalogData = try JSONSerialization.data(
            withJSONObject: ["schemaVersion": 1, "features": featureObjects],
            options: [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
        )
        catalogData.append(0x0A)
        let catalogURL = root.appendingPathComponent("Sources/ZenPackageMetadata/feature-catalog.json")
        try writeOrCheck(catalogData, at: catalogURL, check: check)

        let swiftData = Data(renderSwift(features).utf8)
        let swiftURL = root.appendingPathComponent("Sources/ZenPackageMetadata/ZenBundledFeatureCatalog.swift")
        try writeOrCheck(swiftData, at: swiftURL, check: check)
        print(check ? "Feature catalog generation is deterministic and current." : "Generated feature catalog (\(features.count) entries).")
    }

    static func writeOrCheck(_ data: Data, at url: URL, check: Bool) throws {
        if check {
            guard (try? Data(contentsOf: url)) == data else {
                throw GeneratorError("generated file is stale: \(url.path)")
            }
        } else {
            try data.write(to: url, options: .atomic)
        }
    }

    static func renderSwift(_ features: [Feature]) -> String {
        let entries = features.map { feature in
            """
                    ZenBundledFeatureMetadata(
                        id: \(literal(feature.id)),
                        productName: \(literal(feature.productName)),
                        sourceRelativePath: \(literal(feature.sourceRelativePath)),
                        isInstalledOnLinux: \(feature.isInstalledOnLinux),
                    )
            """
        }.joined(separator: ",\n")
        return """
        //
        //  ZenBundledFeatureCatalog.swift
        //  Generated by Scripts/GenerateFeatureCatalog.swift. Do not edit by hand.
        //

        public struct ZenBundledFeatureMetadata: Sendable, Equatable, Hashable {
            public let id: String
            public let productName: String
            public let sourceRelativePath: String
            public let isInstalledOnLinux: Bool

            public init(id: String, productName: String, sourceRelativePath: String, isInstalledOnLinux: Bool) {
                self.id = id
                self.productName = productName
                self.sourceRelativePath = sourceRelativePath
                self.isInstalledOnLinux = isInstalledOnLinux
            }
        }

        public enum ZenBundledFeatureCatalog {
            public static let declarativeCatalogFilename = "feature-catalog.json"

            public static let all: [ZenBundledFeatureMetadata] = [
        \(entries)
            ]

            public static func feature(id: String) -> ZenBundledFeatureMetadata? {
                all.first { $0.id == id }
            }

            public static var linuxInstallerProductNames: [String] {
                all.filter(\\.isInstalledOnLinux).map(\\.productName)
            }
        }
        """ + "\n"
    }

    static func literal(_ value: String) -> String {
        "\"" + value.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"") + "\""
    }

    struct GeneratorError: LocalizedError {
        let message: String
        init(_ message: String) { self.message = message }
        var errorDescription: String? { message }
    }
}


do {
    try GenerateFeatureCatalog.run()
} catch {
    fatalError(error.localizedDescription)
}
